#!/bin/bash
#
# Copyright (C) 2020-2022 by alexaTeam@Github, < https://github.com/alexaTeam >.
#
# This file is part of < https://github.com/alexaTeam/alexa > project,
# and is released under the "GNU v3.0 License Agreement".
# Please see < https://github.com/alexaTeam/alexa/blob/master/LICENSE >
#
# All rights reserved.

exec python3 tools/genstr.py
