SOFT_RESTART = 1
HARD_RESTART = 2

FETCH_CORE = 3
FETCH_REPOS = 4

GET_CORE = 5
GET_REPOS = 6

ADD_REPO = 7
REMOVE_REPO = 8

GET_CORE_NEW_COMMITS = 9
GET_CORE_OLD_COMMITS = 10

GET_REPO_NEW_COMMITS = 11
GET_REPO_OLD_COMMITS = 12

SET_CORE_BRANCH = 13
SET_CORE_VERSION = 14

SET_REPO_BRANCH = 15
SET_REPO_VERSION = 16
SET_REPO_PRIORITY = 17

REMOVE_PLUGINS = 18
RESTORE_PLUGINS = 19
GET_REMOVED_PLUGINS = 20
CLEAR_REMOVED_PLUGINS = 21

INVALIDATE_REPOS_CACHE = 22

SET_ENV = 23
UNSET_ENV = 24
